security:
    firewalls:
        public:
            pattern: ^/(css|js|images|favicon.ico)
            security: false

        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout

            security: true

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
