security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        public:
            pattern: ^/(css|js|images|favicon.ico)
            security: false

        main:
            pattern: ^/
            stateless: false
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginAuthenticator
            form_login:
                login_path: /login
                check_path: /login
                enable_csrf: false
            logout:
                path: /logout

