controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
error:
    path: /error
    controller: App\Controller\ErrorController
    methods: [POST, GET]

app_login:
    path: /login
    controller: App\Controller\UserController::login
    
app_register:
    path: /register
    controller: App\Controller\UserController::register

home:
    path: /
    controller: App\Controller\HomeController::index
    
